version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-doctorat
    environment:
      POSTGRES_USER: doctorat
      POSTGRES_PASSWORD: doctorat
      # DB par défaut créée à la création du conteneur (les autres seront créées par les services)
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - doctorat-net

  service-auth:
    build: ./serviceAuth           # chemin vers le module
    container_name: service-auth
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: doctorat
      DB_PASSWORD: doctorat
    ports:
      - "8081:8081"
    networks:
      - doctorat-net
    restart: unless-stopped

  inscription-service:
    build: ./inscription-service
    container_name: inscription-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: inscriptions_db
      DB_USER: doctorat
      DB_PASSWORD: doctorat
    ports:
      - "8083:8083"
    networks:
      - doctorat-net
    restart: unless-stopped

  soutenances-service:
    build: ./soutenances-service
    container_name: soutenances-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: soutenances_db
      DB_USER: doctorat
      DB_PASSWORD: doctorat
    ports:
      - "8082:8082"
    networks:
      - doctorat-net
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  doctorat-net:
