server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**

        # ðŸ§© Route for Inscription Service (all 3 controllers)
        - id: inscription-service-auth-route
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**

        - id: inscription-service-accounts-route
          uri: http://localhost:8081/
          predicates:
            - Path=/accounts/**

        - id: inscription-service-profile-route
          uri: http://localhost:8081/
          predicates:
            - Path=/profile/**


info:
  app:
    name: GateWay
    description: Microservice for API management
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.security: INFO